### ISSUE TITLE
[Build Thread] Soldering finished

### ISSUE THREAD

**Issue by Knarf2807** [howie-j/OpenSolder#4]
Next steps:
Checking the voltages
Waiting for OLED
Flashing the software

![IMG20221210220050.jpg](https://user-images.githubusercontent.com/58421457/206875560-f910ec3d-e52d-45fc-ae6b-bcc909ab927b.jpg)

**Comment by howie-j** [comment]
Cool! I'll get working on publishing the firmware then!

**Comment by howie-j** [comment]
Did you have any issues sourcing components, ordering the PCB or during assembly/soldering?

**Comment by Knarf2807** [comment]
> Did you have any issues sourcing components, ordering the PCB or during assembly/soldering?

The order at jlcpcb with your gerber files was without any issue. Perfect! Thank you for your work.
I had to replace the LDO (AP2111H-3.3 -> LM1117 3.3 (AliExpress-Version)). It is pin-comaptible and works fine with other 5V-Sources.
And the fuse holder was not in stock (digikey). I replaced it with it's THR-pendant Schurter 3-132-873. Without a problem.

The rest of the BOM was a mix from Digikey and LCSC. Why a mix? The STM32 was only available at LCSC but not the Hirose Connector. But I didn't want a long search for a STM32-Replacement. For R6, C9 and C10 I took 0603-SMDs because I had it "in stock".

It's easy to solder with some SMD-experiences. Only the Hirose Connector was a little bit to narrow on the 24VAC-Connector as I came with my big 1,6mm chisel. But that was my fault.

Thank you for that good job. I like the Hardware.

Btw: You can see the "temp-overjumping" at an Ersa-Iron too. With a brand new Ersa you can see it in this video (time 9:25...): https://www.youtube.com/watch?v=CfsMkEtcwEI

Frank

**Comment by howie-j** [comment]
Sorry for the slow reply, a bit busy at the moment. The mix of parts from Distrelec, Digikey and LCSC is mostly because i used whatever i had in stock. If there were any significant interrest in the project i could do a revision and simplify the BOM, perhaps only using JLCPCB stock parts etc. However github is full of soldering station project so thats probably not going to happen :)

I should probably make a PCB assembly instruction, as you probably found out you should solder the Hirose connector before the 24VAC terminal block, to get better access to the pins.

I managed to work on the firmware this weekend, and made some progress. I probably wont have time to finish a "beta" version until christmas/new years, however i could give you a link with the previous working version if you wish!

**Comment by Knarf2807** [comment]
Hello! Oh... No problem. I'm very bussy to. Just Today the Display arrived, the cardridges are still on the way to me (it's my first JBC-Station) and i have to put the whole stuff in the case. I have time. :-)
When I'll be ready I send you a message. 

For the assembly instruction: If you solder the Hirose-connector first, it's hard to solder the AC terminal block. The worst Hirose-Pin is the middle. It is not collected. So my favorite for the instruction would be: "To solder the middle pin is not necessary.". But at the end it was my dump fault. 

Yes, github is full of stations. But I think there are many I don't like. Your station has a good schematic. And it looks very beautiful. That's why I hope it will work. :-)
I ordered a stand from china. When it will arrive I give you a feedback if it is a good choice.

**Comment by Knarf2807** [comment]
First impression: looks fine and does it's job. I have to finish the case.

Thank you very much for your work. I will test it in the next weeks and give you more feedback. 

![IMG20230124190427.jpg](https://user-images.githubusercontent.com/58421457/214395770-a5e45989-fd9e-4ac1-8249-85f2519d226a.jpg)

**Comment by Knarf2807** [comment]
!!! FINISHED !!! And I love it!

Now you can see, why it took so long. I "redesigned" the enclosure, mainly to have the hirose-connector on the back. 

So I put the PCB on the back. For that I have to use a cable directly (not a plug) and the switch moved aproximatly 1 cm outside. Not my favorite design, but in practice it doesn't matter because you don't see it and you can feel it good. 
On the front now I only need the display and the encoder. The 230V fuse is now in the enclosure (a cable-fuse-holder).

But why?
1. I like the clean front
2. I found this China-stand. It is cheaper than the original JBC-Tip-holder from the bom and is an out of the box stand.

I modified the stand, so that it communicates with the station. I changed the very simple PCB inside. Now the "Handpiece in stand"- and "tip-change"-event works with the china-stand. The cable-holder is an original from JBC. For communication between stand and station I use pin 3 and 4 from the Hirose-connector.

I didn't find a nice connector for the programming interface. So I put a cable inside and have to screw off the front. 

That's all, I think. Now the pictures:

![IMG20230208190559](https://user-images.githubusercontent.com/58421457/217634850-77463228-f64e-4a88-9169-20824b530d79.jpg)
![IMG20230208190647](https://user-images.githubusercontent.com/58421457/217634854-f39cdced-e595-494f-8c6b-65a798bd7080.jpg)
![IMG20230208190721](https://user-images.githubusercontent.com/58421457/217634858-7fc1ec24-c781-4195-b3fb-7ef4341a4f8d.jpg)


Thanks a lot again for your work. :-)

Frank

**Comment by howie-j** [comment]
Congratulations, thats really cool!

I was also contemplating placing the tool connector on the rear of the unit, but decided against it to simplify the build. I might look into doing that on a v2 someday!

**Comment by Knarf2807** [comment]
Than I am your man. 😁

I didn't think it completly over, but I think the best way for that are two PCBs. One POWER-PCB on the back and one controller-board in the front. But with less cables as possible...

In my enclosure it is very tide between transformer and PCB. Not the best solution for 230V.

Thank you very much for your feedback.

**Comment by howie-j** [comment]
Closing this issue, but feel free to give an update if you find any bugs or annoyances that should be adressed 👍

**Comment by BBroadbent** [comment]
Hi @Knarf2807 would you mind sharing the link (or product name) to the soldering stand you've used - looks great

**Comment by howie-j** [comment]
Hi @BBroadbent, i would guess Knarf used the AIXUN T3A Stand, you can find it on aliexpress.
